### ISSUE TITLE
Confirm that data aren't being filtered to just chinook

### ISSUE THREAD

**Issue by alvizek** [FlowWest/edi-feather-snorkel#3]
There may be a line of code in Erin's original Rmd used to create the dataset that filters to Chinook. Double check and remove. We want all species included.

**Comment by MaddeeRubenson** [comment]
You were right - the species were limited to `c("CHN", "NONE", "CHNU", "CHNT", "CHNC", "CHNF", "CHNS")`

all species included are: 
 "CHN"     "RBTS"    "RBTC"    "NONE"    "SASQ"    "SMB"     "RBT"     "LMB"     "SASQ/HH" "SASU"    "LAM"     NA        "WAG"     "SCP"     "SPD"     "MIN"     "TP"      "BGS"     "HH"      "RES"    "MQF"     "CHNS"    "SHAD"    "UNKSALM" "AS"      "RE"      "GSN"     "BAS"     "CHNU"    "0"       "CHNF"    "WAR"     "CHNT"    "SNF"     "CHNC"    "AMS"     "GS"      "GSF"    

I'll look into the naming conventions because some of these are unknown to me. Will review the Snorkel_Revised.mdb to see if I can identify the naming conventions.

**Comment by MaddeeRubenson** [comment]
update: included all species in dataset which is reflected in va-feather-river-analysis and updated in https://github.com/SRJPE/JPE-datasets/tree/203-update-feather-river-section-names

note: the data has not yet been pushed to the cloud because i want to wait on confirmation from questions sent this week to Casey related to the dataset including ones related to section names.

**Comment by ErinCain** [comment]
updated data in this package to be all species. Also updated in liz's PR "200-add-feather-early-snorkel"
